# From ocaml/ocaml:debian-stable
# To: A local switch build of a recent opam

FROM ocaml/ocaml:debian-stable

ARG ocaml_version="4.07.0"
ARG opam_version="1.2"

LABEL distro_style="apt" \
      operatingsystem="linux" \
      distro="debian" \
      distro_long="debian-stable" arch="x86_64" \
      ocaml_version="$ocaml_version" \
      opam_version="$opam_version"

RUN apt-get -y update && \
  DEBIAN_FRONTEND=noninteractive apt-get -y upgrade && \
  DEBIAN_FRONTEND=noninteractive apt-get -y install aspcud && \
  git clone -b $opam_version git://github.com/ocaml/opam /tmp/opam && \
  sh -c "cd /tmp/opam && make cold && make install && echo Not installing OPAM2 wrappers && rm -rf /tmp/opam" && \
  echo 'opam ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/opam && \
  chmod 440 /etc/sudoers.d/opam && \
  chown root:root /etc/sudoers.d/opam && \
  adduser --disabled-password --gecos '' opam && \
  passwd -l opam && \
  chown -R opam:opam /home/opam

USER opam
ENV HOME /home/opam
WORKDIR /home/opam

RUN mkdir .ssh && \
  chmod 700 .ssh && \
  git config --global user.email "docker@example.com" && \
  git config --global user.name "Docker CI" && \
  sudo -u opam sh -c "git clone -b master git://github.com/ocaml/opam-repository" && \
  sudo -u opam sh -c "opam init -a -y --comp $ocaml_version /home/opam/opam-repository" && \
  sudo -u opam sh -c "opam install -y depext travis-opam"
